# Exports
export ZSH="$HOME/.oh-my-zsh"

# Python Virtualenvwrapper exports and source
export VIRTUALENVWRAPPER_LOG_DIR="$WORKON_HOME"
export VIRTUALENVWRAPPER_HOOK_DIR="$WORKON_HOME"
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/work

source ~/.local/bin/virtualenvwrapper.sh

# My oh-my-zsh theme
ZSH_THEME="robbyrussell"

# Pluguins
plugins=(
    git 
    zsh-autosuggestions 
    ant-zsh 
    zsh-syntax-highlighting
    autopep8
    docker
    command-not-found
    jsontools
)

source $ZSH/oh-my-zsh.sh

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='vi'
fi

# ssh
export SSH_KEY_PATH="~/.ssh/rsa_id"

# Aliases
alias code='code-insiders'
alias CD='cd'
alias LS='ls'
alias sl='ls'
alias SL='sl'
alias celar='clear'